---  
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: null
  creationTimestamp: null
  labels:
    io.service: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.service: webserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: null
      creationTimestamp: null
      labels:
        io.network/app-network: "true"
        io.service: webserver
    spec:
      containers:
        - image: nginx:alpine
          name: webserver
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: webserver-claim1
      restartPolicy: Always
      volumes:
        - name: webserver-claim1
          configMap:
            name: webserver-claim1
---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  creationTimestamp: null
  labels:
    io.service: app
  name: app
spec:
  type: ClusterIP
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.service: app
---  
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: app-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.network/app-network: "true"
  podSelector:
    matchLabels:
      io.network/app-network: "true"
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: null
  creationTimestamp: null
  labels:
    io.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.service: app
  strategy: {}
  template:
    metadata:
      annotations:

      creationTimestamp: null
      labels:
        io.network/app-network: "true"
        io.service: app
    spec:
      containers:
        - env:
            - name: SERVICE_NAME
              value: app
          image: cavamagie/react-compressor-node
          name: react-compressor-node
          ports:
            - containerPort: 3000
          resources: {}
          tty: true
      restartPolicy: Always
---
apiVersion: v1
data:
  app.conf: |

    server {
    listen 80;
    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/public;
    location / {
       proxy_pass http://app.monitoring-dev:3000;
    }
    } 

kind: ConfigMap
metadata:
  name: webserver-claim1

---  
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    io.service: webserver  
  name: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
    - port: 443
      nodePort: 30443
      name: https
  selector:
    io.service: webserver 
---
